### ISSUE TITLE
finding tootik posts

### ISSUE THREAD

**Issue by snan** [dimkr/tootik#17]
Hi!

I wanted to reply to this post gemini://hd.206267.xyz/view/77572017c3e3303677a7a1430179c23a452d25c91dc5b11b5ce602f531a0e229 from my Akkoma instance but I didn't know what to search for in there.

wget --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -qO- "htt ps://hd.206267.xyz/user/dimkr"|jq|less

That worked fine, but the outbox address doesn't seem to work:

wget --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -qO- https://hd.206267.xyz/outbox/dimkr|less

Nor can I do this:

wget --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -qO- https://hd.206267.xyz/view/77572017c3e3303677a7a1430179c23a452d25c91dc5b11b5ce602f531a0e229 
I tried grepping through Tootik's golang source code for hints, too.
Tootik is such a good idea. Thank you for starting this project.

**Comment by dimkr** [comment]
> That worked fine, but the outbox address doesn't seem to work:

This API is not implemented (yet?).

Saving of historical data (so you can fetch all posts by a newly-followed user) increases complexity and storage requirements. In addition, your instance should contain this post if you follow the author, because this post is sent to your instance.

(I know, this means you can reply to a post from a tootik instance only if you follow the author, or any other user on the same instance follows the author, otherwise you can't access the post)

I'll see what I can do, it shouldn't be hard to save the Create activity when a new post is created, then implement an /outbox API that lists Create activities by user x.

**Comment by dimkr** [comment]
@snan Please try now, I implemented basic support for this (no idea how to test compatibility, because I don't know what triggers requests to /outbox/%s in Mastodon)

**Comment by snan** [comment]
You can try

    wget --header 'Accept: application/ld+json; profile="https://www.w3.org/ns/activitystreams"' -qO- https://hd.206267.xyz/view/77572017c3e3303677a7a1430179c23a452d25c91dc5b11b5ce602f531a0e229
    
to test. I still got nothing

**Comment by dimkr** [comment]
I only implemented /outbox/%s so far, not direct access to posts.

**Comment by snan** [comment]
You li'l scoundrel ♥ 
Yeah, outbox works fine now

**Comment by dimkr** [comment]
@snan Try now, you should be able to fetch posts over HTTPS - the ID of a post is now a working HTTPS URL and not just an opaque identifier

```
$curl -s https://hd.206267.xyz/outbox/dimkr | jq -r .first
https://hd.206267.xyz/outbox/dimkr?01694268286
```
(first page of dimkr's outbox)

```
$ curl -s https://hd.206267.xyz/outbox/dimkr?01694268286 | jq -r '.orderedItems[0].object.id'
https://hd.206267.xyz/post/8189787ffae14a8bfd03bb2fbb21045adb98265de8784e1f2c910b68ea9d8129
```
(object ID of first activity in dimkr's outbox, assuming it's a Create activity of a Note object)

```
$ curl -s https://hd.206267.xyz/post/8189787ffae14a8bfd03bb2fbb21045adb98265de8784e1f2c910b68ea9d8129 | jq
{
  "@context": "https://www.w3.org/ns/activitystreams",
  "attributedTo": "https://hd.206267.xyz/user/dimkr",
  "cc": [
    "https://hd.206267.xyz/followers/dimkr"
  ],
  "content": "Test public post after big refactor",
  "id": "https://hd.206267.xyz/post/8189787ffae14a8bfd03bb2fbb21045adb98265de8784e1f2c910b68ea9d8129",
  "published": "2023-09-09T14:04:46.602422143Z",
  "tag": null,
  "to": [
    "https://www.w3.org/ns/activitystreams#Public"
  ],
  "type": "Note",
  "url": "gemini://hd.206267.xyz/view/83708f1c8cc781380460991578904f5b8dbec95f997490d7a9e160f89c5b3f27"
}
```
(the Note object associated with this ID)

**Comment by dimkr** [comment]
More improvements (still not pushed):
1. Post ID is now a working HTTPS URL and the user is redirected to Gemini if the browser requests HTML
2. Post title is now link identical to its ID now (previously it wasn't, because tootik did not expose posts over HTTPS and links were broken)
3. /outbox and /post output is a bit cleaner, because data is saved in a more complete form and gets cleaned up when the HTTP response is built

**Comment by snan** [comment]
I still haven't been able to pull them into Akkoma, even after all this hard work that you've put in so far.

**Comment by snan** [comment]
It works now!

I curl the outbox and jq the json to find the post id's, but, once I have them, they work!! Awesome!

**Comment by snan** [comment]
The problem now is…

going from https://hd.206267.xyz/post/3a4394793f81dff0a0e1c254a20e641740f249664c2966610c342a5ae430f85e to gemini://hd.206267.xyz/view/7568b84fa11f6f1b0818cbeb266ec814fa997013c66f9c1c9d86b46297275867 (for example) is easy, I just 

    wget --max-redirect=0 --server-response --header "Accept: text/html" https://hd.206267.xyz/post/3a4394793f81dff0a0e1c254a20e641740f249664c2966610c342a5ae430f85e

Or, saving a request, I can do

    echo -n https://hd.206267.xyz/post/3a4394793f81dff0a0e1c254a20e641740f249664c2966610c342a5ae430f85e|sha256sum

and that gives me the id on the gemini side which I can add to a /view/ url.

But going the other direction is not so easy. I can only reply to posts that are new enough to still be in the json outbox.
