### ISSUE TITLE
Aggressive rate-limiting

### ISSUE THREAD

**Issue by locrianz** [dimkr/tootik#31]
So with everything else going on, I didn't think to mention this, but it is a bit annoying.

If I post from Tootik, even just one time, I can't post again for at least a minute; there's an error page that says "Please wait before posting again". This makes posting threads a bit annoying, especially since the character limit on Tootik seems to be fairly small. Is this intended behavior?

(On that note, account creation was disabled for an *hour* when I first launched the service, but I was willing to accept that as a one-time hurdle. Was that intended?)

**Comment by dimkr** [comment]
Everything is intentional, PRs that make rate limiting optional or configurable are welcome (I have bigger things to work on before I find the time).

https://github.com/dimkr/tootik/blob/4cd66f18504413034c9bbfa74b279e116115e63d/front/post.go#L63

https://github.com/dimkr/tootik/blob/4cd66f18504413034c9bbfa74b279e116115e63d/front/post.go#L72

https://github.com/dimkr/tootik/blob/4cd66f18504413034c9bbfa74b279e116115e63d/front/register.go#L119

**Comment by dimkr** [comment]
It's configurable now
